### ISSUE TITLE
Hi please whats the pr i am new to this and i need your sample code to create something

### ISSUE THREAD

**Issue by AlfredSharon** [carsonip/alexa-whatsapp#2]
Hi please whats the pr i am new to this and i need your sample code to create something

**Comment by carsonip** [comment]
2 years ago when I created this project, the utterances and intents were not stored in a file but only in Alexa's developer console. Now I do not have access to them any more. I'm afraid you'll have to work them out by yourself.

You may consider this project to be incomplete due to the missing utterances and intents, although it shouldn't be hard to find the intents when you look into the code.

**Comment by AlfredSharon** [comment]
ok thanks alot 
i'd try do that but I just started coding 
in your free time if you can point some out i'd be really grateful
thanks for your help though. really appreciate

**Comment by carsonip** [comment]
Congratulations on starting coding.

I would say this is not a good starter project for a beginner. It involves setting up a Python server on the cloud (e.g. Heroku), setting up an Amazon Lambda function and creating an Alexa skill.

For starter Alexa projects, I suggest that you follow a tutorial: https://developer.amazon.com/alexa-skills-kit/alexa-skill-quick-start-tutorial-nodejs

To learn a new programming language, try [Codecademy](https://www.codecademy.com/)

Good luck and have fun.

**Comment by AlfredSharon** [comment]
wow already chose this for my Final Year project now i'm stuck.
am conversant with all those i meant new to javascript programming though still learning. thanks for pointing out the python server part.
i'd stop disturbing please just drop down all the tools needed. is there anything else apart from Lambda, Alexa, and Python Server, 
i have gone through a process and my skill can only say welcome to talking whatsapp
A brief process please and i will take it from there. Thanks
